on:
  pull_request:
     branches:
       - sources

name: 📦 Check build

jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v1

      - name: Install rmarkdown, blogdown # might need knitr
        run: Rscript -e 'install.packages(c("rmarkdown","blogdown"))'

      - name: Install hugo
        run: Rscript -e 'blogdown::install_hugo(arch = "universal")'

      - name: Build site with blogdown
        run: Rscript -e "blogdown::build_site()"
