on:
  push:
     branches:
       - sources


name: 🚀 Build and Deploy

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install rmarkdown, blogdown # might need knitr
        run: Rscript -e 'install.packages(c("rmarkdown","blogdown"))'

      - name: Install hugo
        run: Rscript -e 'blogdown::install_hugo(version = "0.122.0", arch = "universal")'

      - name: Build site with blogdown
        run: Rscript -e "blogdown::build_site()"

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: master # The branch the action should deploy to.
          folder: public # The folder the action should deploy.


# site is built on sources branch, deploy on master branch
